name: CI de la app

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependencias y compilar
        run: mvn install

      - name: Ejecutar tests
        run: mvn test

      - name: Login en DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t miusuario/miapp:latest -t miusuario/miapp:${{ github.sha }} .

      - name: Subir imagen a DockerHub
        run: |
          docker push miusuario/miapp:${{ github.sha }}